#!/bin/ash
# Copyright (C) 2006-2011 OpenWrt.org

readonly APP_DATA_SEC_OTHER_KEY_FILE="/data/app_data/sec_other_key"
readonly APP_DATA_SEC_OTHER_KEY_TMP_FILE="/tmp/sec_other/sec_other_key"
readonly APP_DATA_SEC_OTHER_KEY_CHANGE_FLAG="/tmp/sec_other/sec_other_key_change"
readonly APP_DATA_SEC_OTHER_NONCE_NAME="sec_other_nonce"
readonly APP_DATA_SEC_OTHER_DBG_INFO="/tmp/sec_other/dbginfo.txt"
readonly APP_DATA_MTD_NAME="app_data"
readonly APP_DATA_MAP_NAME="app_data_enc"
readonly APP_DATA_VOL_NAME="app_data_vol"
readonly APP_DATA_VIR_MTD_NAME="app_data_vir"

APP_DATA_VIR_MTD_NUM=""

mount_app_data_sec_other_log_console() {
	echo "$*" |tee /dev/console >/dev/null
	echo "[sec_dbg] $@" >> "$APP_DATA_SEC_OTHER_DBG_INFO"
}

mount_sec_other_key_init() {
	if [ -s "$APP_DATA_SEC_OTHER_KEY_FILE" ]; then
		cp -a "$APP_DATA_SEC_OTHER_KEY_FILE" "$APP_DATA_SEC_OTHER_KEY_TMP_FILE"
		mount_app_data_sec_other_log_console "app_data key get succeed."
		return 0
	fi

	local sn=$(nvram show | grep -E ^SN=)
	local uuid=$(cat /proc/sys/kernel/random/uuid)
	local nonce="$APP_DATA_SEC_OTHER_NONCE_NAME=$uuid"

	printf "%s\n%s\n" "${sn}" "${nonce}" \
		| sort \
		| openssl dgst -binary -sha512 \
		| tee "$APP_DATA_SEC_OTHER_KEY_TMP_FILE" >/dev/null

	cp -a "$APP_DATA_SEC_OTHER_KEY_TMP_FILE" "$APP_DATA_SEC_OTHER_KEY_FILE"
	touch "$APP_DATA_SEC_OTHER_KEY_CHANGE_FLAG"
	sync
	mount_app_data_sec_other_log_console "app_data key init succeed."
}

mount_app_data_mtd() {
	local ret=1
	local vid="0"
	local maj=""
	local min=""
	local mtd_dev=""
	local mtd_new=""
	local mtd_magic=""
	local dest="/data/$APP_DATA_MTD_NAME"

	mtd_new=$(grep -c ^mtd /proc/mtd)
	mtd_dev=$(grep -w "${APP_DATA_MTD_NAME}" /proc/mtd | awk -F: '{print substr($1,4)}')
	APP_DATA_VIR_MTD_NUM="$mtd_new"

	insmod seccrypt
	echo 1 >/sys/kernel/crypto/seccrypt/fixed_sec_key
	dmsetup create "$APP_DATA_MAP_NAME" --table "0 16384 crypt aes-cbc-qce-essiv:sha256 a7f67ad520bd83b9725df6ebd76c3eee 0 /dev/mtdblock${mtd_dev} 0"
	insmod block2mtd.ko "block2mtd=/dev/mapper/$APP_DATA_MAP_NAME,0x20000,$APP_DATA_VIR_MTD_NAME,$APP_DATA_MTD_NAME"

	[ -c /dev/mtd${mtd_new} ] || {
		maj=$(cat /sys/class/mtd/mtd${mtd_new}/dev | awk -F':' '{print $1}')
		min=$(cat /sys/class/mtd/mtd${mtd_new}/dev | awk -F':' '{print $2}')
		mknod /dev/mtd${mtd_new} c "${maj}" "${min}"
	}

	# format mtd
	nanddump --bb=skipbad --omitoob --length=2048 -f /tmp/ubi_data_firstpage.bin "/dev/mtd$mtd_new" > /dev/null 2>&1
	mtd_magic=$(hexdump -C -n 4 /tmp/ubi_data_firstpage.bin | awk 'NR<2 {print $2$3$4$5}')
	if [ "$mtd_magic" != "55424923" ]; then
		echo "create new $APP_DATA_MTD_NAME ubi." > /dev/console
		[ -c "/dev/ubi$mtd_dev" ] && ubidetach -p "/dev/mtd$mtd_new" > /dev/null 2>&1
		ubiformat "/dev/mtd$mtd_new" --yes > /dev/console 2>&1
	fi

	rm -f /tmp/ubi_data_firstpage.bin

	# attach mtd
	ubiattach /dev/ubi_ctrl --devn="$mtd_dev" --mtdn="$mtd_new" -b 160
	maj=$(cat < "/sys/class/ubi/ubi$mtd_dev/dev"|awk -F':' '{print $1}')
	min=$(cat < "/sys/class/ubi/ubi$mtd_dev/dev"|awk -F':' '{print $2}')
	[ -c "/dev/ubi${mtd_dev}" ] || mknod "/dev/ubi${mtd_dev}" c "$maj" "$min"
	ubinfo -d "${mtd_dev}" -N "$APP_DATA_VOL_NAME" >/dev/null 2>&1 || {
		ubimkvol "/dev/ubi$mtd_dev" --vol_id="$vid" --name="$APP_DATA_VOL_NAME" --maxavsize
	}

	# mount mtd
	mkdir -p "$dest"

	if mount "ubi${mtd_dev}_${vid}" -t ubifs "$dest"; then
		ret=0
		mount_app_data_sec_other_log_console "app_data mount succeed"
	else
		mount_app_data_sec_other_log_console "FATAL: [$i] $APP_DATA_MTD_NAME mount fail."
	fi

	echo 3 > /proc/sys/vm/drop_caches

	if [ $ret -ne 0 ]; then
		#force erase mtd
		mount_app_data_sec_other_log_console "FATAL: try erase /dev/mtd${mtd_dev}"
		mtd erase "/dev/mtd${mtd_dev}"
	fi

	return $ret
}

umount_app_data_mtd() {
	umount /data/app_data
	ubidetach -p "/dev/mtd${APP_DATA_VIR_MTD_NUM}"
	rmmod block2mtd.ko
	dmsetup remove "/dev/mapper/$APP_DATA_MAP_NAME"
	echo 0 > /sys/kernel/crypto/seccrypt/fixed_sec_key
}

mount_app_data() {
	local ret=1

	mkdir -p "${APP_DATA_SEC_OTHER_KEY_TMP_FILE%/*}"

	for i in $(seq 3); do
		mount_app_data_sec_other_log_console "[$i] Attempt to remount partition $APP_DATA_MTD_NAME"
		if mount_app_data_mtd; then
			ret=0
			break
		else
			umount_app_data_mtd
		fi
	done

	if [ $ret -eq 0 ]; then
		mount_sec_other_key_init
		umount_app_data_mtd
	else
		mount_app_data_sec_other_log_console "FATAL: app_data key init failed."
	fi
}

boot_hook_add preinit_main mount_app_data
