#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

#. /lib/miwifi/storage/storage.sh

START=99
NAME=baidupan
USE_PROCD=1
PROG=/usr/sbin/baidupan

check_bindstatus() {
   local uuid="$(uci -q get baidupan.user.uuid)"
   local mount_path="$(storage_get_mount_path_by_uuid $uuid)"

   if [ -z "$mount_path" ];then
        echo "[Baidupan]: wrong disk, please bind right disk " >> /tmp/messages
       exit 0
   fi
}

init_baidupan() {

    #check_bindstatus

    local dis=$(block info | awk -F 'MOUNT' '{print $2}' | awk -F '\"' 'NR==1{print $2}')
    [ -z "$dis" ] && {
        echo "error: please install USB" >> /tmp/messages
        exit 0
    }

    [ -d "$dis/.baidupan/tmp" ] && {
        rm -rf $dis/.baidupan/tmp
    }
    mkdir -p $dis/.baidupan/tmp

    [ -d "/tmp/baidupan" ] && {
        rm -rf /tmp/baidupan
    }
    mkdir -p /tmp/baidupan

    /usr/sbin/kill_baidupan.sh
}

start_service(){
    init_baidupan

    [ -f "$PROG" ] && {
	    procd_open_instance
	    procd_set_param command ${PROG}
	    procd_set_param respawn
	    procd_close_instance
    }
}

stop_service() {
    service_stop ${PROG}
}

restart_service() {
    service_reload ${PROG}
}
