#!/bin/sh /etc/rc.common
#
# Copyright (c) 2022 Qualcomm Technologies, Inc.
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.
#

START=00

boot() {
	local cnss2_args=""
	local cnssdaemon_log_file=""
	local cnssd_args=""

	for arg in $(cat /proc/cmdline); do
		case "$arg" in
			cnss2*)
				arg="$(echo $arg | awk -F '.' '{print$2}')"
				cnss2_args="$cnss2_args $arg"
				;;
		esac
	done

	echo "Loading cnss2: $cnss2_args" > /dev/console
	insmod ipq_cnss2 "$cnss2_args"

	if [ ! -z "$cnssdaemon_log_file" ];then
		cnssd_args=" -dddd -f $cnssdaemon_log_file"
	else
		cnssd_args=" -s"
	fi

	/usr/bin/cnssdaemon $cnssd_args &
}

