#!/bin/sh /etc/rc.common

USE_PROCD=1
START=91
STOP=05

RUN_DIR="/tmp/miot_central"
BASE_PROFILE=/etc/profile.d/docker.sh

start_service() {
	if ! which docker >/dev/null; then
		[ -f "$BASE_PROFILE" ] && . "$BASE_PROFILE"
	fi

	mkdir -p "$RUN_DIR"

	procd_open_instance
	procd_set_param command mdnsd -debug
	procd_set_param respawn
	procd_close_instance

	procd_open_instance
	procd_set_param env PATH="$PATH"
	procd_set_param command miotcentralctld -c "$RUN_DIR/centralCtl.sock"
	procd_set_param respawn
	procd_close_instance
}

stop_service() {
	reset=$(nvram get restore_defaults)
	touch /tmp/central_normal_stop

	if [ "${reset:-0}" = "0" ]; then
		miot_centralctld_hook.sh wait_update 30
		miotcentralctl reboot
		sleep 4
	else
		miotcentralctl restore
		sleep 4
		central_software_pack.sh stop
		central_software_pack.sh rm
	fi
}
