#!/bin/sh /etc/rc.common
#
# Copyright (c) 2020-2021,2023 Qualcomm Technologies, Inc.
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.
#

. /lib/wifi/qcawificfg80211.sh
START=11

boot_wifi() {
	if grep -q 'skip_wifi' /proc/cmdline; then
		echo "skipping wifi load" > /dev/console
		exit 0
	fi
	echo "loading qca-wifi" > /dev/kmsg
	[ -e /tmp/.wifi-config-done ] && {
		return
	}

	echo "boot_wifi wifi detect" > /dev/console
	/sbin/wifi config "1" > /tmp/wireless.tmp
	[ -s /tmp/wireless.tmp ] && {
		cat /tmp/wireless.tmp >> /etc/config/wireless
	}
	rm -f /tmp/wireless.tmp

	[ -s /etc/config/wireless ] && {
		touch /tmp/.wifi-config-done
	}

	[ -f /lib/modules/*/ecm-wifi-plugin.ko ] && [ -d /sys/module/ecm ] && {
		insmod ecm-wifi-plugin.ko
	}

	echo "qca-wifi loaded" > /dev/kmsg
}

boot_dependency() {
	[ -f /lib/modules/*/qca-ssdk.ko ] && {
		insmod qca-ssdk.ko
	}
	[ -f /lib/modules/*/qca-nss-ppe.ko ] && {
		modprobe qca-nss-ppe.ko
	}
	[ -f /lib/modules/*/qca-nss-dp.ko ] && {
		insmod qca-nss-dp.ko
	}
	[ -f /lib/modules/*/qca-nss-drv.ko ] && {
		insmod qca-nss-drv.ko
	}
	[ -f /lib/modules/*/cfg80211.ko ] && {
		insmod cfg80211.ko
	}
	[ -f /lib/modules/*/qca-nss-ppe-vp.ko ] && {
		insmod qca-nss-ppe-vp.ko
	}
}

boot_owrt_le() {
	if grep -q 'skip_wifi' /proc/cmdline; then
		echo "Skipping QCA WiFi load" > /dev/console
		exit 0
	fi

	# Set board_name for the target
	if [ ! -d /tmp/sysinfo ]; then
		mkdir -p /tmp/sysinfo
	fi
	echo "ap-sdxpinn-qcn9224" > /tmp/sysinfo/board_name

	echo "Loading QCA WiFi modules" > /dev/kmsg
        if [ $(lsmod | grep -c ipq_cnss2) = 0  ];then
		echo "Loading ipq_cnss2" > /dev/kmsg
		KO_PATH="$(get_ap_sdxpinn_ko_path)"
		insmod $KO_PATH/ipq_cnss2.ko log_level=4 enable_mlo_support=0 skip_radio_bmap=0x4
	fi

	# Kill cnssdaemon if already started
	cnssd_pid=$(pgrep cnssdaemon)
	[ ! -z "$cnssd_pid" ] && {
		echo "*****Kill cnssdaemon pid=$cnssd_pid******" > /dev/console
		kill $cnssd_pid
	}

	# Start cnssdaemon
	local cnssdaemon_log_file=""
	local cnssd_args=""
	if [ ! -z "$cnssdaemon_log_file" ];then
		cnssd_args=" -dddd -f $cnssdaemon_log_file"
	else
		cnssd_args=" -s"
	fi

	echo "*****Start cnssdaemon******" > /dev/console
	/usr/bin/cnssdaemon $cnssd_args &

	[ -e /tmp/.wifi-config-done ] && {
                echo "WiFi modules already loaded" > /dev/kmsg
		return
	}

	/sbin/wifi config > /tmp/wireless.tmp
	[ -s /tmp/wireless.tmp ] && {
		cat /tmp/wireless.tmp >> /etc/config/wireless
	}
	rm -f /tmp/wireless.tmp

	[ -s /etc/config/wireless ] && {
		touch /tmp/.wifi-config-done
	}

	echo "Done loading QCA WiFi modules" > /dev/kmsg
}

boot() {
	if [ ! -f /sys/firmware/devicetree/base/model ] || [ $(grep -c "SDXPINN" /sys/firmware/devicetree/base/model) = 0 ]; then
		boot_dependency
		boot_wifi
	else
		boot_owrt_le
	fi
}

