#!/bin/sh

uuid=$(uci -q get mi_docker.settings.device_uuid)

if [ -z "$uuid" ] || [ -z "$DEVICE" ] || [ -z "$MOUNTPATH" ]; then
	exit 0
fi

if [ "$ACTION" = "add" ]; then
	# Check device match
	if storage uuid "$DEVICE" | grep -sqx "$uuid"; then
		# Ignore event during boot up, wait for normal init
		if ! grep -sqx boot_done /tmp/boot_check_done; then
			exit 0
		fi

		logger -t "mi_docker[$$]" "hotplug start"
		/etc/init.d/mi_docker start
	fi
elif [ "$ACTION" = "remove" ]; then
	# Check whether dockerd running path match $MOUNTPATH
	if pgrep -l dockerd | awk '{print $2}' | grep -sqE "^$MOUNTPATH/"; then
		logger -t "mi_docker[$$]" "hotplug stop"
		/etc/init.d/mi_docker stop
	fi
fi
