#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
NAME=firewall_cpp
PROG=/usr/sbin/${NAME}

start_service() {
    procd_open_instance
    procd_set_param command ${PROG}
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger ${NAME}
    procd_add_reload_trigger ${NAME}_dist
    procd_add_reload_trigger MiwifiEvent_wireless_changed
}

reload_service() {
    start
}
