#!/bin/sh /etc/rc.common
# Copyright (c) 2022 Qualcomm Technologies, Inc.
#
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.
#

START=0


. /lib/functions.sh


update_ini()
{
    #Update licenses_info.ini containing the license files names

    local lib_firmware_lic_path=$1
    local licenses_info_ini="license_info.ini"

    ls ${lib_firmware_lic_path}*.pfm > ${lib_firmware_lic_path}${licenses_info_ini}
    echo "License info created successfully" > /dev/console
}

copy_lic_to_firmware()
{
    local firmware_path_ipq5332="/lib/firmware/IPQ5332/"
    local firmware_path_qcn9224="/lib/firmware/qcn9224/"
    local license_path="/license"

    if [ -d "$firmware_path_ipq5332" ]; then
        rm ${firmware_path_ipq5332}*.pfm
        ln -sf ${license_path}/*.pfm ${firmware_path_ipq5332}.
        update_ini $firmware_path_ipq5332
    elif [ -d "$firmware_path_qcn9224" ]; then
        rm ${firmware_path_qcn9224}*.pfm
        ln -sf ${license_path}/*.pfm ${firmware_path_qcn9224}.
        update_ini $firmware_path_qcn9224
    else
        echo "/lib/firmware path is not available" > /dev/console
        exit 1;
    fi



}

read_licenses_from_rootfs()
{
    local license_path="/license"
    local rootfs_license_path="/license/pfm"
    local license_upgrade_path=$1
    local upgrade_mode=$2

    mkdir -p ${license_path}
    rm ${license_path}/*.pfm

    mkdir -p ${rootfs_license_path}


    #if license upgarde using license-pfm-upgrade script
    if [ -n "$license_upgrade_path" ]; then

        if [ "$upgrade_mode" == "UPGRADE" ]; then
            rm ${rootfs_license_path}/*.pfm
        fi

        cp ${license_upgrade_path}/*.pfm ${rootfs_license_path}/.
    fi

    files=$(ls ${rootfs_license_path}/*.pfm | wc -l)

    if [ $files -eq 0 ]; then
        echo "No PFM license files in rootfs" > /dev/console
    else
        cp ${rootfs_license_path}/*.pfm ${license_path}/.
        copy_lic_to_firmware
        echo "PFM License files loaded successfully" > /dev/console
    fi

}

boot()
{

    local mtdblock=$(find_mtd_part 0:LICENSE)

    local temp="/tmp"
    local license="/license"

    local use_rootfs=$(cat /sys/module/license_manager/parameters/use_license_from_rootfs)
    if [ $use_rootfs -gt 0 ]; then
        echo "Trying to read license files from rootfs image" > /dev/console
        read_licenses_from_rootfs
        exit 0;
    fi

    if [ -z "$mtdblock" ]; then
        # read from mmc
        mtdblock=$(find_mmc_part 0:LICENSE)
    fi

    if [ -z "$mtdblock" ]; then
        echo "No License partition in device" > /dev/console
        echo "Trying to read license files from rootfs image" > /dev/console
        read_licenses_from_rootfs
        exit 0;
    fi

    # load license_tar.gz

    mkdir -p ${temp}

    dd if=${mtdblock} of=${temp}/license.tar.gz bs=2K conv=sync

    mkdir -p ${temp}/license
    tar -xzf ${temp}/license.tar.gz -C ${temp}/license/.

    mkdir -p ${license}
    rm -f ${license}/*.pfm


    files=$(ls ${temp}/license/*.pfm | wc -l)

    if [ $files -eq 0 ]; then
        echo "No PFM license files in partition to load" > /dev/console
    else
        cp ${temp}/license/*.pfm ${license}/.
        echo "PFM License files loaded successfully" > /dev/console
    fi

    copy_lic_to_firmware

    #Clear the temp files and directory
    rm ${temp}/license.tar.gz
    rm -rf ${temp}/license

}

