#!/bin/sh /etc/rc.common

START=96
STOP=15
NAME=mi_docker
USE_PROCD=1

EXTRA_COMMANDS="$EXTRA_COMMANDS install uninstall install_portainer uninstall_portainer check_docker_env"
EXTRA_COMMANDS="$EXTRA_COMMANDS ui_install ui_uninstall check_installed check_portainer check_bins get_disk_size"
EXTRA_COMMANDS="$EXTRA_COMMANDS is_running uciadd ucidel limit_resource cancel_install cancel_install_portainer"
EXTRA_COMMANDS="$EXTRA_COMMANDS check_integrity"
EXTRA_HELP=$(echo "$EXTRA_COMMANDS" | grep -oE '[_a-z]+' | sed 's/^/\t/')

MIWIFI_CDN="https://cdn.cnbj1.fds.api.mi-img.com/opensource/rc01/docker"
DEVICE_UUID=$(uci -q get mi_docker.settings.device_uuid)
STORAGE_DIR=$(storage dump | grep -C3 "${DEVICE_UUID:-invalid-uuid}" | grep target: | awk '{print $2}')
STORAGE_SIZ=$(storage dump | grep -C3 "${DEVICE_UUID:-invalid-uuid}" | grep size: | awk '{printf "%d", $2/2}')
DOCKER_DIR="${STORAGE_DIR:=/not_exist_disk}/mi_docker"
DOCKER_VER="20.10.17"
DOCKER_MD5="f9b6570a174df41aec6b822fba7a17aa"
DOCKER_TGZ="$DOCKER_DIR/docker-$DOCKER_VER.tgz"
PAUTHZ_VER="0.8.21d1e54b"
PAUTHZ_MD5="57b864290172e4181ca7e9cf53bba28e"
PAUTHZ_BIN="opa-docker-authz"
PAUTHZ_TGZ="$DOCKER_DIR/${PAUTHZ_BIN}_$PAUTHZ_VER.tgz"
MANAGE_VER="0.0.7.2"
MANAGE_MD5="56990437e055c5dd00494eb63156dd39"
MANAGE_BIN="simple-docker"
MANAGE_TGZ="$DOCKER_DIR/${MANAGE_BIN}_$MANAGE_VER.tgz"
DOCKER_BIN="$DOCKER_DIR/docker-binaries"
DOCKER_BIN_LIST="containerd containerd-shim ctr docker dockerd docker-init docker-proxy runc $PAUTHZ_BIN $MANAGE_BIN"
DOCKER_CONF_DIR="/tmp/dockerd"
DOCKERD_CONF="${DOCKER_CONF_DIR}/daemon.json"
PAUTHZ_CONF="/var/run/docker/opa/authz.rego"
CGROUP_DIR="/sys/fs/cgroup/docker"
STATIC_BIN=$(uci -q get mi_docker.settings.static_bin)
STATIC_DIR=$(uci -q get mi_docker.settings.static_dir)
DOCKER_UCB="/etc/docker-up.d"

if [ -n "$STATIC_BIN" ]; then
	DOCKER_BIN="$STATIC_BIN"
	DOCKER_DIR="${STATIC_DIR:-/tmp/docker}"
fi

logdbg() {
	[ -z "$DEBUG" ] && return
	logger -p debug -t "mi_docker[$$]" "DEBUG: $1"
}

loginfo() {
	logger -p info -t "mi_docker[$$]" "INFO: $1"
}

logerr() {
	logger -p error -t "mi_docker[$$]" "ERROR: $1"
}

is_running() {
	# Instead to '/etc/init.d/xxx running' after procd upgraded
	ubus call service list | jsonfilter -q -e "@.mi_docker.instances.instance1.running" | grep -sqw true
}

check_installed() {
	test -d "$DOCKER_DIR"
}

check_portainer() {
	"$DOCKER_BIN/docker" ps | grep -sqw "$MANAGE_BIN"
}

check_bins() {
	test -x "$DOCKER_BIN/dockerd"
}

get_disk_size() {
	df -h | grep -m1 "$STORAGE_DIR$" | awk '{print $2}' | xargs printf
}

check_docker_env() {
	local size="$((${STORAGE_SIZ:-0} / 1000 / 1000))"

	if [ -n "$STATIC_BIN" ]; then
		# Ignore storage check
		return 0
	fi

	if storage dump | wc -l | grep -sqw 0; then
		logerr "error: no USB devices"
		exit 1
	fi

	if [ ! -d "$STORAGE_DIR" ]; then
		logerr "ext4 device not found"
		exit 2
	fi

	if [ "${size:-0}" -lt 32 ]; then
		logerr "disk size(${size}G) should be greater than 32G"
		exit 3
	fi

	if [ "1" != "$(uci -q get mi_docker.mi_docker.settings.docker_verify)" ]; then
		logerr "mtd docker verify failed"
		exit 4
	fi
}

check_file_md5() {
	local md5="$1"
	local file="$2"

	if ! md5sum "$file" | grep -sq "$md5"; then
		logerr "$file md5 not match"
		exit 4
	fi
}

gen_integrity() {
	local md5
	local file

	for file in $DOCKER_BIN_LIST; do
		md5=$(md5sum "$DOCKER_BIN/$file" | awk '{print $1}')
		uci set "mi_docker.md5.${file//-/_}"="$md5"
	done
	uci commit mi_docker
}

valid_mountpath() {
	local file="$1"
	local filter="$2"
	local sock="/var/run/docker.sock"

	cat < "$file" | jsonfilter -e "$filter" | cut -d: -f1 |
		while read -r path; do
			real="$path"
			[ "$path" != "$sock" ] && real=$(readlink -f "$path")

			if ! echo "$real" | grep -qsE "^($STORAGE_DIR|$sock)"; then
				logerr "$file mount source $path invalid"
				echo 1
				break
			fi
		done
}

check_mountpoint() {
	find "$DOCKER_DIR/lib/docker/containers" -name "config.v2.json" |
		while read -r file; do
			valid_mountpath "$file" '@.MountPoints.*.Spec.Source'
		done

	find "$DOCKER_DIR/lib/docker/containers" -name "hostconfig.json" |
		while read -r file; do
			valid_mountpath "$file" '@.Binds.*'
		done
}

check_integrity() {
	local md5
	local file

	[ -n "$STATIC_BIN" ] && return 0

	for file in $DOCKER_BIN_LIST; do
		md5=$(uci -q get "mi_docker.md5.${file//-/_}")
		check_file_md5 "${md5:-xxxx}" "$DOCKER_BIN/$file"
	done

	[ -n "$(check_mountpoint)" ] && exit 6

	return 0
}

download_file() {
	local dst="$1"
	local url="$2"
	local md5="$3"
	local max=3
	local ite=

	for ite in $(seq "$max"); do
		curl -L -o "$dst" "$url" 2>/dev/null || continue
		md5sum "$dst" | grep -sq "$md5" && return 0
	done

	logerr "download ${dst##*/} failed!"
	return "$ite"
}

remove_docker() {
	for i in $(seq 10); do
		rm -rf "$DOCKER_DIR"
		[ ! -d "$DOCKER_DIR" ] && break
		usleep $((100000 * i))
	done

	if [ ! -d "$DOCKER_DIR" ]; then
		loginfo "remove $DOCKER_DIR successfully in $i times."
	else
		logerr "failed to remove $DOCKER_DIR!"
	fi
}

install_docker() {
	logdbg "install in dir: $DOCKER_DIR"

	if [ -d "$DOCKER_DIR" ]; then
		loginfo "already installed, force delete first!"
		remove_docker
	fi

	mkdir -p "$DOCKER_DIR"

	# Always download from CDN, do not try to fix incorrect bins
	if ! download_file "$DOCKER_TGZ" "$MIWIFI_CDN/${DOCKER_TGZ##*/}" "$DOCKER_MD5"; then
		remove_docker
		return 1
	fi

	if ! download_file "$PAUTHZ_TGZ" "$MIWIFI_CDN/plugin/${PAUTHZ_TGZ##*/}" "$PAUTHZ_MD5"; then
		remove_docker
		return 2
	fi

	if ! download_file "$MANAGE_TGZ" "$MIWIFI_CDN/${MANAGE_TGZ##*/}" "$MANAGE_MD5"; then
		remove_docker
		return 3
	fi

	# Extract docker binaries
	tar -zxf "$DOCKER_TGZ" -C "$DOCKER_DIR"
	rm -rf "$DOCKER_BIN"
	mv "$DOCKER_DIR/docker" "$DOCKER_BIN"
	tar -zxf "$PAUTHZ_TGZ" -C "$DOCKER_BIN"
	mv "$MANAGE_TGZ" "$DOCKER_BIN/$MANAGE_BIN"

	gen_integrity

	logdbg "install success!"
}

uninstall_docker() {
	stop_service
	remove_docker
}

create_portainer() {
	gzip -d -c "$DOCKER_BIN/$MANAGE_BIN" |
		"$DOCKER_BIN/"docker load

	"$DOCKER_BIN/"docker rm -f "$MANAGE_BIN"
	"$DOCKER_BIN/"docker run -d -p 9001:4050 --name="$MANAGE_BIN" --restart=always \
		-v /var/run/docker.sock:/var/run/docker.sock \
		"$MANAGE_BIN:$MANAGE_VER"
}

install_portainer() {
	if ! create_portainer; then
		exit 5
	fi

	uci -q batch <<-EOF
		set mi_docker.settings.portainer_install="1"
		commit mi_docker
	EOF
}

uninstall_portainer() {
	logdbg "uninstall_portainer"
	"$DOCKER_BIN/"docker rm -f "$MANAGE_BIN"
}

stop_containers() {
	"$DOCKER_BIN/"docker ps -aq | xargs "$DOCKER_BIN"/docker stop
}

install() {
	check_docker_env

	if ! install_docker; then
		logerr "install failed!"
		uci -q delete mi_docker.settings.device_uuid
		uci commit mi_docker
		exit 1
	fi
}

uninstall() {
	uninstall_docker
}

ui_install() {
	install

	uci -q batch <<-EOF
		set mi_docker.settings.docker_install="1"
		commit mi_docker
	EOF
}

ui_uninstall() {
	if [ -d "$DOCKER_DIR" ]; then
		uninstall
	fi

	uci -q batch <<-EOF
		set mi_docker.settings.portainer_install="0"
		set mi_docker.settings.docker_install="0"
		commit mi_docker
	EOF
}

cancel_install() {
	kill_descendant_processes "$(pgrep -f 'mi_docker ui_install' | head -n1)"

	# Ignore cancel if service enabled
	if uci -q get mi_docker.settings.docker_enable | grep -sqw 1; then
		exit 0
	fi

	uci -q delete mi_docker.settings.device_uuid
	ui_uninstall
}

cancel_install_portainer() {
	kill_descendant_processes "$(pgrep -f 'mi_docker install_portainer' | head -n1)"

	uci -q set mi_docker.settings.portainer_install='0'
	uci commit mi_docker

	uninstall_portainer
}

json_add_array_string() {
	json_add_string "" "${1}"
}

process_config() {
	local exec_root data_root log_level iptables bip

	# reset configuration
	rm -fr "${DOCKER_CONF_DIR}"
	mkdir -p "${DOCKER_CONF_DIR}"

	config_load 'mi_docker'

	config_get exec_root globals exec_root "$DOCKER_DIR/run/docker/"
	config_get data_root globals data_root "$DOCKER_DIR/lib/docker/"
	config_get log_level globals log_level "warn"
	config_get_bool iptables globals iptables "1"

	# Don't add these options by default
	# omission == docker defaults
	config_get log_driver globals log_driver ""
	config_get bip globals bip ""
	config_get registry_mirrors globals registry_mirrors ""
	config_get hosts globals hosts ""
	config_get dns globals dns ""
	config_get_bool ipv6 globals ipv6 ""
	config_get ip globals ip ""
	config_get fixed_cidr globals fixed_cidr ""
	config_get fixed_cidr_v6 globals fixed_cidr_v6 ""
	config_get authorization_plugins globals authorization_plugins ""

	. /usr/share/libubox/jshn.sh
	json_init
	json_add_string "bridge" "br-docker"
	[ -z "${exec_root}" ] || json_add_string "exec-root" "${exec_root}"
	json_add_string "data-root" "${data_root}"
	json_add_string "log-level" "${log_level}"
	json_add_object "log-opts"
	json_add_string "max-size" "50m"
	json_close_object
	json_add_boolean "iptables" "${iptables}"
	[ -z "${log_driver}" ] || json_add_string "log-driver" "${log_driver}"
	[ -z "${bip}" ] || json_add_string "bip" "${bip}"
	[ -z "${registry_mirrors}" ] || json_add_array "registry-mirrors"
	[ -z "${registry_mirrors}" ] || config_list_foreach globals registry_mirrors json_add_array_string
	[ -z "${registry_mirrors}" ] || json_close_array
	[ -z "${hosts}" ] || json_add_array "hosts"
	[ -z "${hosts}" ] || config_list_foreach globals hosts json_add_array_string
	[ -z "${hosts}" ] || json_close_array
	[ -z "${dns}" ] || json_add_array "dns"
	[ -z "${dns}" ] || config_list_foreach globals dns json_add_array_string
	[ -z "${dns}" ] || json_close_array
	[ -z "${ipv6}" ] || json_add_boolean "ipv6" "${ipv6}"
	[ -z "${ip}" ] || json_add_string "ip" "${ip}"
	[ -z "${fixed_cidr}" ] || json_add_string "fixed-cidr" "${fixed_cidr}"
	[ -z "${fixed_cidr_v6}" ] || json_add_string "fixed-cidr-v6" "${fixed_cidr_v6}"
	[ -z "${authorization_plugins}" ] || json_add_array "authorization-plugins"
	[ -z "${authorization_plugins}" ] || config_list_foreach globals authorization_plugins json_add_array_string
	[ -z "${authorization_plugins}" ] || json_close_array
	json_dump >"${DOCKERD_CONF}"

	# Ignore to create authorization plugin config if authorization_plugins is empty
	[ -z "${authorization_plugins}" ] && return 0

	mkdir -p "${PAUTHZ_CONF%/*}"
	cat <<-EOF >"$PAUTHZ_CONF"
		package docker.authz
		default allow = false
		allow {
		  not deny
		}
		deny {
		  input.Body.HostConfig.CapAdd[_] != null
		}
		deny {
		  input.Body.HostConfig.Privileged == true
		}
		deny {
		  m = input.Body.HostConfig.Binds[_]
		  not regex.match("^(/mnt/usb-[^:]+|/var/run/docker.sock):[^:]+$", m)
		}
		deny {
		  m = input.BindMounts[_].Resolved
		  not regex.match("^(/mnt/usb-[^:]+|/(var|tmp)/run/docker.sock)$", m)
		}
	EOF
}

limit_resource() {
	local cfg=
	local val=
	local off=

	off=$(uci -q get mi_docker.settings.cgroup_off)
	[ "$off" = 1 ] && return 0

	# Enable clone_children before dir created
	# Ref: https://stackoverflow.com/a/28355516
	echo 1 >"${CGROUP_DIR%/*}/"cgroup.clone_children
	mkdir -p "$CGROUP_DIR"

	# Get CPU limit, 0.5/cores as default
	cfg=$(uci -q get mi_docker.cgroup.cpu)
	val=$(echo "${cfg:-0.5}" | awk '{printf "%d\n", 100000*$1}')
	echo "$val" >"$CGROUP_DIR/"cpu.cfs_quota_us

	# Get MEM limit, 256MB as default, collect children's stats
	cfg=$(uci -q get mi_docker.cgroup.mem)
	val=$(echo "${cfg:-256}" | awk '{printf "%d\n", 1024*1024*$1}')
	echo "$val" >"$CGROUP_DIR/"memory.limit_in_bytes
	echo "$val" >"$CGROUP_DIR/"memory.soft_limit_in_bytes
	echo "1" >"$CGROUP_DIR/"memory.use_hierarchy
}

start_service() {
	check_docker_env

	if uci -q get mi_docker.settings.docker_install | grep -sqw 1; then
		if [ ! -d "$DOCKER_DIR" ]; then
			install
		fi
	fi

	# Check whether enabled from UI
	if uci -q get mi_docker.settings.docker_enable | grep -sqw 0; then
		logdbg "not enabled"
		return
	fi

	check_integrity

	mkdir -p "$DOCKER_DIR/run"

	limit_resource
	process_config

	# In some scenarios, /var/run/docker.sock maybe a directory, cause docker cannot be started
	# See https://github.com/moby/moby/issues/30348
	[ -d /var/run/docker.sock ] && rm -rf /var/run/docker.sock

	procd_open_instance
	procd_set_param stderr 1
	procd_set_param env PATH="$PATH:$DOCKER_BIN"
	procd_set_param command "$DOCKER_BIN/"dockerd --config-file="${DOCKERD_CONF}"
	procd_set_param respawn
	procd_set_param cgroup "$CGROUP_DIR/tasks"
	procd_close_instance

	if [ -d "$DOCKER_UCB" ]; then
		find "$DOCKER_UCB" -type f -exec sh -c 'sh $1 &' _ {} \;
	fi

	# Ignore to start authz if it's config not exist
	[ ! -e "$PAUTHZ_CONF" ] && return 0

	procd_open_instance
	procd_set_param command "$DOCKER_BIN/$PAUTHZ_BIN" -policy-file "$PAUTHZ_CONF"
	procd_set_param respawn
	procd_set_param cgroup "$CGROUP_DIR/tasks"
	procd_close_instance
}

kill_descendant_processes() {
	local pids="$1"
	local pid
	local children
	local child

	for pid in $pids; do
		children="$(pgrep -P "$pid")"

		# 1. kill children if exist
		for child in $children; do
			# Iterate as DFS
			kill_descendant_processes "$child"
		done

		# 2. kill original process
		kill -9 "$pid"
	done
}

stop_service() {
	if is_running; then
		[ -x "$DOCKER_BIN/$PAUTHZ_BIN" ] && service_stop "$DOCKER_BIN/$PAUTHZ_BIN"
		rm -rf "/var/run/docker/"

		service_stop "$DOCKER_BIN/dockerd"

		# Do some deinit to avoid edge case
		# 1. kill containerd-shim and all sub-processes
		kill_descendant_processes "$(pgrep containerd-shim | xargs)"

		# 2. umount docker netns and overlay, need to read from /proc/mounts
		grep "$DOCKER_DIR" /proc/mounts | awk '{print $2}' | sort -r | xargs -r -n1 umount
	fi
}

check_other_enc_mount() {
	if mount | grep "/dev/mapper/other_enc on /data/other type ext4" 2>&- >&-; then
		logerr "other_enc mount success"
		return 0
	else
		logerr "other_enc mount failed"
		return 1
	fi
}

verify_extra_mtd() {
	local name="$1"
	local pem_file="/usr/share/xiaoqiang/verify_extra_mtd.pem"
	local sign_file="/data/$name/$name.digest.sign"
	local digest_file="/tmp/$name.digest"
	local mtd_dev file file_list

	mtd_dev=$(grep -w "$name" /proc/mtd | awk -F: '{print substr($1,4)}')
	[ -z "$mtd_dev" ]   && { logerr "no mtd: $name"; return 1; }
	[ -f "$pem_file" ]  || { logerr "no pem: $pem_file"; return 1; }
	[ -f "$sign_file" ] || { logerr "no sign: $sign_file"; return 1; }

	# generate digest file
	rm -rf "$digest_file"
	file_list=$(find /data/"$name" -type f | LC_COLLATE=C sort)
	for file in $file_list; do
		[ "$file" = "$sign_file" ] && continue
		sha256sum "$file" | cut -d ' ' -f 1 >> "$digest_file"
	done

	# verify
	if openssl dgst -sha256 -verify "$pem_file" -signature "$sign_file" "$digest_file"; then
		logerr "mtd $name verify success"
		return 0
	else
		logerr "mtd $name verify failed with code $?"
		umount  /data/"$name"
		ubidetach -d "$mtd_dev"
		return 1
	fi
}

boot() {
	local docker_verify=0
	local central_verify=0

	[ -z "$(grep -w "docker" /proc/mtd | awk -F: '{print substr($1,4)}')" ] && {
		uci set mi_docker.settings.docker_verify="1"
		uci set mi_docker.settings.central_verify="1"
		uci commit mi_docker
		start
		return
	}

	{
		check_other_enc_mount && {
			verify_extra_mtd "docker" && docker_verify=1
			verify_extra_mtd "central" && central_verify=1
		}

		uci set mi_docker.settings.docker_verify="$docker_verify"
		uci set mi_docker.settings.central_verify="$central_verify"
		uci commit mi_docker

		[ "1" = "$docker_verify" ] && start
	} &
}
