#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

NAME=miio_bt
MIIO_CONFIG="/data/local/miio_bt/"

version_gt() { test "$(echo "$@" | tr " " "\n" | sort -n | head -n 1)" != "$1"; }

start_service() {
	if [ "$(uci -q get miio_ot.ot.bound)" = "1" ]; then
		[ ! -d $MIIO_CONFIG ] && {
			mkdir -p $MIIO_CONFIG
		}

		txpwr=$(uci -q get miio_ot.bt.txpwr)

		procd_open_instance
		procd_set_param command /usr/sbin/miio_bt -l 1
		if [ "$txpwr" ]; then
			procd_append_param command -p "$txpwr"
		fi
		#${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
		procd_set_param respawn 60 5 10
		procd_close_instance
	fi
}
