#!/bin/sh /etc/rc.common
#
# Copyright (c) 2017,2023 Qualcomm Technologies, Inc.
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.
#

#
# Copyright (c) 2016, The Linux Foundation. All rights reserved.
#
USE_PROCD=1
START=13
NAME=qca-hostapd

HOSTAPD_BIN="/usr/sbin/hostapd_wrapper"
PID_FILE="/var/run/hostapd-global.pid"
GLOBAL_CFG="/var/run/hostapd/global"
LOG_FILE="/tmp/hostapd.txt"

start_service() {
    mkdir -p $(dirname $PID_FILE)
    mkdir -p $(dirname $GLOBAL_CFG)
    
    procd_open_instance
    procd_set_param command $HOSTAPD_BIN -g $GLOBAL_CFG -P $PID_FILE -f $LOG_FILE 
    procd_set_param respawn
    procd_set_param pidfile $PID_FILE
    procd_close_instance
}

stop_service() {
	killall hostapd
}

reload_service() {
    sleep 20
    wifi &
    return 0
}
