ro.sys.name=Xiaomi router BE6500
ro.sys.model=xiaomi.router.rd08
ro.sys.vendor=xiaomi
ro.sys.priority=192.0.0
ro.sys.rsyncport=873
ro.sys.mipsport=8884
ro.sys.webcfgport=8086
ro.sys.mqttport=18883
ro.sys.veventsiid=7
ro.sys.phylist=[{"name":"br-lan","type":"ethernet"}]
ro.sys.loopback=[]
ro.hdsync.write_delay=180000
