#!/bin/sh

. /lib/functions.sh

find_network_device() {
	local device="${1}"
	local device_section=""

	check_device() {
		local cfg="${1}"
		local device="${2}"

		local type name
		config_get type "${cfg}" type
		config_get name "${cfg}" name

		[ "${type}" = "bridge" ] && [ "${name}" = "${device}" ] &&
			device_section="${cfg}"
	}

	config_load network
	config_foreach check_device device "${device}"

	echo "${device_section}"
}

find_firewall_forwarding() {
	local zone="${1}"
	local forwarding_section=""

	check_forwarding() {
		local cfg="${1}"
		local zone="${2}"

		local dest src
		config_get dest "${cfg}" dest
		config_get src "${cfg}" src

		[ "${dest}" = "wan" ] && [ "${src}" = "${zone}" ] &&
			forwarding_section="${cfg}"
	}

	config_load firewall
	config_foreach check_forwarding forwarding "${zone}"

	echo "${forwarding_section}"
}

uci_quiet() {
	uci -q "$@" >/dev/null
}

uciadd() {
	local iface="docker"
	local device="docker0"
	local zone="docker"

	# Add network interface
	if ! uci_quiet get network.${iface}; then
		uci_quiet add network interface
		uci_quiet rename network.@interface[-1]="${iface}"
		uci_quiet set network.@interface[-1].type="bridge"
		uci_quiet set network.@interface[-1].bridge_empty="1"
		uci_quiet set network.@interface[-1].force_link="1"
		uci_quiet set network.@interface[-1].proto="static"
		uci_quiet set network.@interface[-1].ipaddr="172.17.0.1"
		uci_quiet set network.@interface[-1].netmask="255.255.0.0"
		uci_quiet commit "network.${iface}"
	fi

	# Add firewall zone
	if ! uci_quiet get firewall.${zone}; then
		uci_quiet add firewall zone
		uci_quiet rename firewall.@zone[-1]="${zone}"
		uci_quiet set firewall.@zone[-1].input="ACCEPT"
		uci_quiet set firewall.@zone[-1].output="ACCEPT"
		uci_quiet set firewall.@zone[-1].forward="ACCEPT"
		uci_quiet set firewall.@zone[-1].name="${zone}"
		uci_quiet commit firewall
	fi

	# Add interface to firewall zone
	if uci_quiet get firewall.${zone}; then
		uci_quiet del_list firewall.${zone}.network="${iface}"
		uci_quiet add_list firewall.${zone}.network="${iface}"
		uci_quiet commit firewall
	fi

	# Add forwarding rule
	if [ "$(find_firewall_forwarding "$zone")" = "" ]; then
		uci_quiet add firewall forwarding
		uci_quiet set firewall.@forwarding[-1].dest="wan"
		uci_quiet set firewall.@forwarding[-1].src="$zone"
		uci_quiet commit firewall
	fi
}

uciadd
