#!/bin/sh

ulimit -c unlimited
echo "/tmp/core-%e-%p-%t" > /proc/sys/kernel/core_pattern
hostapd "$@" &
wait $!
exit_status=$?
echo "hostapd exit with status: $exit_status" > /dev/console
if [ $exit_status -gt 128 ]; then
	if [ $exit_status -eq 131 ] || [ $exit_status -eq 134 ] || [ $exit_status -eq 137 ] || [ $exit_status -eq 139 ]; then
		#ABRT QUIT SEGV ILL 
		/usr/bin/lua /usr/sbin/syslog_upload.lua >&2 &
		sleep 12
		/sbin/wifi &
	elif [ $exit_status -eq 129 ] || [ $exit_status -eq 130 ] || [ $exit_status -eq 143 ]; then
		sleep 12
		/sbin/wifi &
	fi
fi
exit $exit_status
